GM.EnemyTypes = {
	["Custom"] = {
		["raidman_pistol"] = {
			["NPC"] = "raidman",
			["Weight"] = 1,
			["Price"] = 0.2,
			["Reward"] = 10,
			["Weapon"] = "weapon_raid_pistol",
			["Health"] = 100,
		},
		["raidman_smg"] = {
			["NPC"] = "raidman",
			["Weight"] = 1,
			["Price"] = 0.6,
			["Reward"] = 10,
			["Weapon"] = "weapon_raid_smg",
			["Health"] = 100,
		},
		["raidman_shotgun"] = {
			["NPC"] = "raidman",
			["Weight"] = 1,
			["Price"] = 0.8,
			["Reward"] = 10,
			["Weapon"] = "weapon_raid_shotgun",
			["Health"] = 100,
		},
	},
	--[[["CCA"] = {
		--[[
		["cop_stunstick"] = {
			["NPC"] = "npc_metropo zlice",
			["Weapon"] = "weapon_stunstick",
			["Weight"] = 4,
			["Price"] = 0.3,
			["Reward"] = 5,
			["DamageScale"] = 2,
		},
		["cop_pistol"] = {
			["NPC"] = "npc_metropolice",
			["Weapon"] = "weapon_pistol",
			["Weight"] = 3,
			["Price"] = 0.4,
			["Reward"] = 8,
		},
		["cop_smg"] = {
			["NPC"] = "npc_metropolice",
			["Weapon"] = "weapon_smg1",
			["Weight"] = 3,
			["Price"] = 0.5,
			["Reward"] = 10,
		},
	["cop_smg_manhack"] = {
			["NPC"] = "npc_metropolice",
			["Weapon"] = "weapon_smg1",
			["Weight"] = 2,
			["Price"] = 0.6,
			["Reward"] = 11,
			["Manhack"] = true,
		},
		["npc_manhack"] = {
			["NPC"] = "npc_manhack",
			["Weight"] = 1,
			["Price"] = 0.1,
			["Reward"] = 3,
		},
		["npc_cscanner"] = {
			["NPC"] = "npc_cscanner",
			["Weight"] = 1,
			["Price"] = 0.1,
			["Reward"] = 2,
		},
	},
	["Rebels"] = {
		["npc_citizen_pistol"] = {
			["NPC"] = "npc_citizen",
			["Weapon"] = "weapon_pistol",
			["Weight"] = 2,
			["Price"] = 0.4,
			["Reward"] = 5,
		},
		["npc_citizen_smg"] = {
			["NPC"] = "npc_citizen",
			["Weapon"] = "weapon_smg1",
			["Weight"] = 3,
			["Price"] = 0.7,
			["Reward"] = 10,
			["Rebel"] = true,
		},
		["npc_citizen_shotgun"] = {
			["NPC"] = "npc_citizen",
			["Weapon"] = "weapon_shotgun",
			["Weight"] = 4,
			["Price"] = 1,
			["Reward"] = 13,
			["Rebel"] = true,
		},
		["npc_citizen_ar2"] = {
			["NPC"] = "npc_citizen",
			["Weapon"] = "weapon_ar2",
			["Weight"] = 2,
			["Price"] = 1.5,
			["Reward"] = 15,
			["Rebel"] = true,
		},
		["npc_vortigaunt"] = {
			["NPC"] = "npc_vortigaunt",
			["Weight"] = 1,
			["Price"] = 1.3,
			["Reward"] = 18,
		},
	},
	["COTA"] = {
		["combine_smg"] = {
			["NPC"] = "npc_combine_s",
			["Weapon"] = "weapon_smg1",
			["Weight"] = 6,
			["Price"] = 0.5,
			["Reward"] = 10,
		},
		["combine_shotgun"] = {
			["NPC"] = "npc_combine_s",
			["Weapon"] = "weapon_shotgun",
			["Weight"] = 4,
			["Price"] = 0.7,
			["Reward"] = 15,
		},
		["combine_ar2"] = {
			["NPC"] = "npc_combine_s",
			["Weapon"] = "weapon_ar2",
			["Weight"] = 4,
			["Price"] = 1.2,
			["Reward"] = 18,
		},
		["combine_elite"] = {
			["NPC"] = "npc_combine_s",
			["Weapon"] = "weapon_ar2",
			["Weight"] = 2,
			["Price"] = 1.5,
			["Reward"] = 23,
			["CustomModel"] = "models/combine_super_soldier.mdl",
			["DamageScale"] = 1.6,
			["HealthScale"] = 2,
		},
		["npc_manhack"] = {
			["NPC"] = "npc_manhack",
			["Weight"] = 2,
			["Price"] = 0.1,
			["Reward"] = 2,
		},
		["npc_clawscanner"] = {
			["NPC"] = "npc_clawscanner",
			["Weight"] = 1,
			["Price"] = 0.1,
			["Reward"] = 3,
		},
	},
	["Zombies"] = {
		["classic"] = {
			["NPC"] = "npc_zombie",
			["Weight"] = 6,
			["Price"] = 0.3,
			["Reward"] = 5,
			["DamageScale"] = 2,
		},
		["npc_fastzombie"] = {
			["NPC"] = "npc_fastzombie",
			["Weight"] = 5,
			["Price"] = 0.5,
			["Reward"] = 7,
			["DamageScale"] = 2,
		},
		["npc_poisonzombie"] = {
			["NPC"] = "npc_poisonzombie",
			["Weight"] = 1,
			["Price"] = 5,
			["Reward"] = 25,
			["DamageScale"] = 2,
		},
		["npc_headcrab"] = {
			["NPC"] = "npc_headcrab",
			["Weight"] = 2,
			["Price"] = 0.1,
			["Reward"] = 3,
			["DamageScale"] = 3,
		},
		["npc_headcrab_black"] = {
			["NPC"] = "npc_headcrab_black",
			["Weight"] = 2,
			["Price"] = 0.5,
			["Reward"] = 10,
		},
		["npc_headcrab_fast"] = {
			["NPC"] = "npc_headcrab_fast",
			["Weight"] = 1,
			["Price"] = 0.2,
			["Reward"] = 4,
			["DamageScale"] = 2.5,
		},
	},
	--]]
};
